services:
  db:
    container_name: foodgram-db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5000:5432"
    env_file: .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: foodgram-backend
    image: dmithint/foodgram-backend:latest
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

  frontend:
    container_name: foodgram-frontend
    image: dmithint/foodgram-frontend:latest
    volumes:
      - frontend_build:/app/result_build

  nginx:
    container_name: foodgram-gateway
    image: nginx:1.25.4-alpine
    volumes:
      - static_volume:/var/html/static
      - media_volume:/var/html/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
